spring.application.name=issue-tracker-api

server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET}

## api
app.frontend-url=${FRONTEND_URL:https://issueflow.site}
resend.api-key=${IF_RESEND_API_KEY}
resend.from=${MAIL_FROM:noreply@issueflow.site}
